### ISSUE TITLE
Xiaomi pad 6s pro 12.4

### ISSUE THREAD

**Issue by 1Alfo** [gajjartejas/MIUIAdsHelper#45]
doesn't work on Xiaomi pad 6S pro 12.4

last update actually seems like a progress because doesn't crash immediately after launching, but I instead shows grey screen and crashes like 5 seconds later

**Comment by gajjartejas** [comment]
Hello,

Thank you for reporting the bug, I will check it and update it soon, this
happened due to the target SDK changed to 34.

Thank you!

**Comment by gajjartejas** [comment]
Hello @1Alfo Issue seems like related to unsupported device language, I have pushed new update to store.
